name: Test

on:
  push

jobs:
  build-issue:
    runs-on: ubuntu-20.04
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Create build pending issue
        run: |
          sudo apt update
          sudo apt install libmariadb-dev libmariadb3 -y
          sudo apt remove python3-pip
          wget https://bootstrap.pypa.io/get-pip.py
          sudo python3 get-pip.py
      #     pip install -U pyopenssl cryptography mariadb==1.0.11 gnupg requests pygit2
      #     python scripts/test.py

      - name: Update
        run: |
          git submodule update --init glibc-cicd
          git submodule update --init riscv-gnu-toolchain
      #     ls
      #     cat glibc-cicd/curator.py
      #     python scripts/test.py
      #     cd riscv-gnu-toolchain
      #     git branch
      #     git checkout master
      #     git branch

      # - name: Test
      #   run: |
      #     python scripts/test.py
      #     python glibc-cicd/curator.py poll
      #     ls
      - name: Show disk usage
        run: |
          # du -sh /opt/*
          # echo "========"
          # du -sh /usr/*
          # echo "========"
          # du -sh /opt/hostedtoolcache/*
          # echo "========"
          # du -sh /usr/lib/*
          # echo "========"
          # du -sh /usr/local/*
          # echo "========"
          # du -sh /usr/local/share/*
          # echo "========"
          # du -sh /usr/share/*
          grep binfmt /proc/mounts
          ls /proc/sys/fs/binfmt_misc
          CUR_DIR=pwd
          cd /proc/sys/fs/binfmt_misc
          
          sudo echo ':qemu-riscv64:M::\x7f\x45\x4c\x46\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xf3\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:$CUR_DIR/riscv-gnu-toolchain/scripts/wrapper/qemu/riscv64-unknown-linux-gnu-run:PCOF' > register
          sudo echo ':qemu-riscv32:M::\x7f\x45\x4c\x46\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xf3\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:$CUR_DIR/riscv-gnu-toolchain/scripts/wrapper/qemu/riscv32-unknown-linux-gnu-run:PCOF' > register
          ls /proc/sys/fs/binfmt_misc
          echo "===="
          cat qemu-riscv64
          echo "==="
          cat qemu-riscv32

      - name: Build linux
        run: |
          cd riscv-gnu-toolchain
          mkdir build
          cd build
          ../configure --prefix=$(pwd) --with-multilib-generator="rv64gc-lp64d--"
          make linux -j $(nproc)
          
      - name: Build qemu
        run: |
          cd riscv-gnu-toolchain
          cd build
          make stamps/build-qemu -j $(nproc)

      - name: Run
        run: |
          cd riscv-gnu-toolchain
          cd build
          make check-glibc-linux -j $(nproc)
      
