name: Test

on:
  push

jobs:
  build-issue:
    runs-on: ubuntu-20.04
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3

      - name: echo arch info
        run: |
          echo $(arch)

      - name: echo arch info
        run: |
          cd dockerfile
          docker build --platform linux/amd64/v4 . -t tester:latest
        continue-on-error: true

      - name: echo arch info
        run: |
          cd dockerfile
          docker build --platform linux/x86_64/v8 . -t tester:latest
        continue-on-error: true

      
      # - name: Build linux
      #   id: some-id
      #   run: |
      #     echo "list=[\"build-glibc-linux-rv64gcv\",\"build-glibc-linux-rv32gcv\"]" >> $GITHUB_OUTPUT
    # outputs:
      # list: ${{ steps.some-id.outputs.list }}
          
  # run-matrix: 
    # needs: [ build-issue ]
    # uses: ./.github/workflows/matrix.yaml
    # strategy:
      # fail-fast: false
      # matrix: 
      #   target:
      #     ${{ fromJson(needs.build-issue.outputs.list) }}
    # with:
      # target: ${{ matrix.target }}
          
