name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main
  

jobs:
  test-job:
    runs-on: ubuntu-22.04
    # if: ${{ github.event.workflow_dispatch == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: echo
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo $GITHUB_CONTEXT

      - name: event
        run: |
          echo ${{ github.event_name }}
      - name: test
        if: ${{ !cancelled() }}
        run: |
          echo "something"

        
  # build-issue:
  #   runs-on: ubuntu-22.04
  #   permissions:
  #     issues: write
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: test
  #       run: |
  #         cat ./test.txt ./test.txt > double.txt
  #         echo "title" > content.md
  #         echo "[download link](./double.txt)" >> content.md
  #         stat double.txt

  #     - name: Upload test
  #       uses: actions/upload-artifact@v4
  #       id: output-id
  #       with:
  #         name: test-summary
  #         path: |
  #           ./content.md
  #         retention-days: 90

  #     - name: test
  #       run: |
  #         echo "title" > new.md
  #         echo "[download link](${{ steps.output-id.outputs.artifact-url }})" >> new.md
  #         stat new.md

  #     - name: Create or update summary issue
  #       uses: peter-evans/create-issue-from-file@v5
  #       id: create-issue
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         content-filepath: ./new.md
  #         title: test

      

      # - name: install dependencies
      #   run: |
      #     sudo apt update
      #     sudo apt install qemu-user-static
      #     sudo apt install binfmt-support
      #     sudo sed -i 's|interpreter .*|interpreter /usr/bin/qemu-riscv64-static|' /usr/share/binfmts/qemu-riscv64
      #     sudo update-binfmts --importdir /usr/share/binfmts --import qemu-riscv64
      #     cat /proc/sys/fs/binfmt_misc/qemu-riscv64
      
      # - name: download things
      #   run: |
      #     wget https://github.com/negge/riscv-vm/releases/download/20231027/RISCV-DevEnv-2023-10-27.tar.xz
      #     tar -xf RISCV-DevEnv-2023-10-27.tar.xz

      # - name: run mounting
      #   run: |
      #     cd RISCV-DevEnv-2023-10-27
      #     sudo mkdir /mnt/gentoo
      #     sudo mount -o loop,offset=1048576 gentoo.img /mnt/gentoo
      #     sudo cp /etc/resolv.conf /mnt/gentoo/etc
      #     sudo mount --bind /proc /mnt/gentoo/proc
      #     sudo mount --bind /sys /mnt/gentoo/sys
      #     sudo mount --bind /dev /mnt/gentoo/dev
      #     sudo mount --bind /dev/pts /mnt/gentoo/dev/pts
      #     sudo mount --bind /dev/shm /mnt/gentoo/dev/shm

      # - name: chroot
      #   run: |
      #     ls
      #     chmod 777 ./run_glibc.sh
      #     sudo cp ./run_glibc.sh /mnt/gentoo/
      #     sudo chroot /mnt/gentoo /bin/bash ./run_glibc.sh
      #     pwd
      #     env-update && source /etc/profile
    
  # run-matrix: 
  #   # needs: [ build-issue ]
  #   uses: ./.github/workflows/matrix.yaml
  #   # strategy:
  #   #   fail-fast: false
  #   #   matrix: 
  #   #     target:
  #   #       ${{ fromJson(needs.build-issue.outputs.list) }}
  #   with:
  #     target: hi
          
