name: Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main
  

jobs:
  test-job:
    runs-on: ubuntu-22.04
    # if: ${{ github.event.workflow_dispatch == 'true' }}
    steps:
      - uses: actions/checkout@v3

      - name: echo
        run: |
          echo ${{ github.event.workflow_dispatch }}
          ISSUE_NAME='Coordination Branch Testsuite Status f3fecf54f0a91e8a9b65e1ce6b984324654b2e2d'
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Token ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/patrick-rivos/gcc-postcommit-ci/issues \
            -o issues.txt
          FOUND_ISSUE=$(cat issues.txt | jq "map(select(.title == \"$ISSUE_NAME\"))" | sed -e s/\n//g)
          OTHER_ISSUE='[]'
          # if no issue of that name is found, jq returns '[]'
          echo "found_issue={$FOUND_ISSUE}" >> $GITHUB_OUTPUT
          echo "other_issue={$OTHER_ISSUE}" >> $GITHUB_OUTPUT
        
  build-issue:
    runs-on: ubuntu-22.04
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3

      - name: test
        run: |
          echo "hi" | grep "something"

      # - name: install dependencies
      #   run: |
      #     sudo apt update
      #     sudo apt install qemu-user-static
      #     sudo apt install binfmt-support
      #     sudo sed -i 's|interpreter .*|interpreter /usr/bin/qemu-riscv64-static|' /usr/share/binfmts/qemu-riscv64
      #     sudo update-binfmts --importdir /usr/share/binfmts --import qemu-riscv64
      #     cat /proc/sys/fs/binfmt_misc/qemu-riscv64
      
      # - name: download things
      #   run: |
      #     wget https://github.com/negge/riscv-vm/releases/download/20231027/RISCV-DevEnv-2023-10-27.tar.xz
      #     tar -xf RISCV-DevEnv-2023-10-27.tar.xz

      # - name: run mounting
      #   run: |
      #     cd RISCV-DevEnv-2023-10-27
      #     sudo mkdir /mnt/gentoo
      #     sudo mount -o loop,offset=1048576 gentoo.img /mnt/gentoo
      #     sudo cp /etc/resolv.conf /mnt/gentoo/etc
      #     sudo mount --bind /proc /mnt/gentoo/proc
      #     sudo mount --bind /sys /mnt/gentoo/sys
      #     sudo mount --bind /dev /mnt/gentoo/dev
      #     sudo mount --bind /dev/pts /mnt/gentoo/dev/pts
      #     sudo mount --bind /dev/shm /mnt/gentoo/dev/shm

      # - name: chroot
      #   run: |
      #     ls
      #     chmod 777 ./run_glibc.sh
      #     sudo cp ./run_glibc.sh /mnt/gentoo/
      #     sudo chroot /mnt/gentoo /bin/bash ./run_glibc.sh
      #     pwd
      #     env-update && source /etc/profile
    
  # run-matrix: 
  #   # needs: [ build-issue ]
  #   uses: ./.github/workflows/matrix.yaml
  #   # strategy:
  #   #   fail-fast: false
  #   #   matrix: 
  #   #     target:
  #   #       ${{ fromJson(needs.build-issue.outputs.list) }}
  #   with:
  #     target: hi
          
