name: Matrix

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  build:
    if: ${{ inputs.self_hosted == 'false' }}
    runs-on: ubuntu-20.04
    environment: production
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3

      - name: echo hi
        run:
          echo '${{ inputs.target }}'

     
